#if defined _entity_manager_menu_included
 #endinput
#endif
#define _entity_manager_menu_included

#define INFO_SIZE 128
#define ITEM_SIZE 128

#define ENTITY_MANAGER "Entity manager"

#define ITEM_ENTITY_FREEZE "Freeze entity"
#define ITEM_ENTITY_UNFREEZE "Unfreeze entity"
#define ITEM_ENTITY_DELETE "Delete entity"
#define ITEM_ENTITY_RESTORE "Restore entity"
#define ITEM_ENTITY_SHOW_PATH "Show path"
#define ITEM_ENTITIES_SAVE "Save entities"
#define ITEM_ENTITIES_LOAD "Load entities"
