#if defined _em_math_included
 #endinput
#endif
#define _em_math_included

#define HALF 0.5

#define X 0
#define Y 1
#define Z 2

#define PITCH 0
#define YAW 1
#define ROLL 2

#define LEFT_FRONT_BOTTOM 0
#define LEFT_FRONT_TOP 1
#define LEFT_REAR_BOTTOM 2
#define LEFT_REAR_TOP 3
#define RIGHT_FRONT_BOTTOM 4
#define RIGHT_FRONT_TOP 5
#define RIGHT_REAR_BOTTOM 6
#define RIGHT_REAR_TOP 7

#define BOUNDS_ROTATE_YES true
#define BOUNDS_ROTATE_NO false
