#if defined _em_menu_included
 #endinput
#endif
#define _em_menu_included

#define MENU_TEXT_MAX_SIZE (32 * 4)

#define ENTITY_MANAGEMENT "Entity management"

#define ACTION_ENTITY_FREEZE "Freeze entity"
#define ACTION_ENTITY_UNFREEZE "Unfreeze entity"
#define ACTION_ENTITY_DELETE "Delete entity"
#define ACTION_ENTITY_RESTORE "Restore entity"
#define ACTION_ENTITIES_SAVE "Save entities"
#define ACTION_ENTITIES_LOAD "Load entities"
