#if defined _em_menu_included
 #endinput
#endif
#define _em_menu_included

#define MENU_TEXT_MAX_SIZE (32 * 4)

#define ENTITY_MANAGEMENT "Entity management"

#define ITEM_ENTITY_FREEZE "Freeze entity"
#define ITEM_ENTITY_UNFREEZE "Unfreeze entity"
#define ITEM_ENTITY_DELETE "Delete entity"
#define ITEM_ENTITY_RESTORE "Restore entity"
#define ITEM_ENTITIES_SAVE "Save entities"
#define ITEM_ENTITIES_LOAD "Load entities"
