#if defined _em_menu_included
 #endinput
#endif
#define _em_menu_included

#define INFO_SIZE 16
#define ITEM_SIZE (32 * 4)

#define ENTITY_MANAGER "Entity manager"

#define ITEM_ENTITY_FREEZE "Freeze entity"
#define ITEM_ENTITY_UNFREEZE "Unfreeze entity"
#define ITEM_ENTITY_DELETE "Delete entity"
#define ITEM_ENTITY_RESTORE "Restore entity"
#define ITEM_ENTITIES_SHOW_PATH "Show path"
#define ITEM_ENTITIES_SAVE "Save entities"
#define ITEM_ENTITIES_LOAD "Load entities"
#define ITEM_OBJECT "Object"

#define ADMIN_MENU "adminmenu"
